<title><?=$form->title->getDisplayValue();?> - <?=$site->title;?></title>
<meta name="description" content="<?=strip_tags($form->text->value);?>">
<meta name="keywords" content="<?=$form->title->getDisplayValue();?>">
<script src="/lib/js/lightbox/jquery.lightbox.js"></script>
<link rel="stylesheet" href="/lib/js/lightbox/jquery.lightbox.css" type="text/css">
<script src="/<?=$site->module . '/js/articles.js';?>"></script>