<p>
    Подготовка материалов: Вера Вершинина
    <img src="/i/vera.jpg"> <a href="mailto:vera.vershinina@ensk.ru">vera.vershinina@ensk.ru</a>
    и Алексей Ермаков
    <img src="/i/alex.jpg"> <a href="mailto:alexei.ermakov@ensk.ru">alexei.ermakov@ensk.ru</a>.
</p><br>
<font size="5pt">Задайте свой вопрос директорам новосибирских фирм</font><br>
Опрос будет производиться по телефону или при личных встречах. Может быть переформулирован.
<form name="add" method="post" action="/articles/add/" enctype="multipart/form-data" class="form">
    <input type="hidden" name="key" value="">
    <textarea id="add_text" name="text" rows="4" cols="17" class="textarea" required></textarea>
    <div class="alert"></div>
    <button type="submit" class="submit">Отправить</button>
    <div class="alert"></div>
</form>
<p style="display: none">
	Спасибо. Ваша тема принята.
</p>
<br><br>
<p>«Новосибирская прибыль» интернет-журнал © 2012 Телестрока ООО. 
    В оформлении использована фоторабота Степанова&nbsp;С.А.&nbsp;"Gelio" по договору передачи прав использования от 27.03.2012. Просим о неточностях, несоответствиях, ущемлениях прав третьих лиц, а так же вопросы и предложения сообщать по
    электронной почте <a href="mailto:info@ensk.ru">info@ensk.ru</a>. Спасибо!
</p>
<?php include($site->partialPath . '/counter.phtml');?>